name: 'render-guides'
description: 'Documentation render tool for typo3 documentation'

inputs:
  input:
    description: 'Input directory'
    default: 'Documentation'
  output:
    description: 'Output directory'
    default: 'RenderedDocumentation'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/jaapio/render-guides:main'

branding:
  icon: 'book-open'
  color: 'orange'
