name: 'render-guides'
description: 'Documentation render tool for typo3 documentation'

inputs:
  input:
    description: 'Input directory'
    required: false
    default: null

  working-directory:
    description: 'Working directory'
    required: false
    default: './'

  config:
    description: 'Configuration file location'
    default: 'Documentation'

  output:
    description: 'Output directory'
    default: 'RenderedDocumentation'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/typo3-documentation/render-guides:main'
  env:
    SHELL_VERBOSITY: '3'
  args:
    - '--working-dir=${{ inputs.working-directory }}'
    - '--config=${{ inputs.config }}'
    - '--output=${{ inputs.output }}'
    - '${{ inputs.input }}'

branding:
  icon: 'book-open'
  color: 'orange'
