name: 'render-guides'
description: 'Documentation render tool for typo3 documentation'

inputs:
  input:
    description: 'Input directory'
    required: false
    default: null

  config:
    description: 'Configuration file location'
    default: 'Documentation'

  output:
    description: 'Output directory'
    default: 'RenderedDocumentation'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/typo3-documentation/render-guides:main'
  args:
    - '--config=${{ inputs.config }}'
    - '--output=${{ inputs.output }}'
    - '${{ inputs.input }}'

branding:
  icon: 'book-open'
  color: 'orange'
