name: CI

on: [push, pull_request]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: |
          yarn install
      - name: Build
        run: |
          yarn frontend
      - name: Status
        run: |
          git status | grep -q "nothing to commit, working tree clean"

  build-render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: |
          yarn install
      - name: Build
        run: |
          yarn render
      - name: Status
        run: |
          git status | grep -q "nothing to commit, working tree clean"
      - name: Archive Demo
        uses: actions/upload-artifact@v1
        with:
          name: demo
          path: build/Result/project/0.0.0
