name: Python Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Build
        run: |
          python setup.py sdist bdist_wheel
      - name: Archive Module
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  sphinx-quickstart-package:
    needs: [package]
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: package
      - name: Install Package
        run: pip install $(find package -name "*.tar.gz")
      - name: Install Sphinx
        run: |
          pip install -U sphinx
      - name: Sphinx Quickstart
        run: |
          sphinx-quickstart --project PROJECT --author AUTHOR --sep --extensions sphinx_typo3_theme --no-use-make-mode --quiet
          sed -i 's/alabaster/sphinx_typo3_theme/g' source/conf.py
      - name: Sphinx Build
        run: |
          sphinx-build -b html source build
      - name: Archive Module
        uses: actions/upload-artifact@v1
        with:
          name: sphinx-quickstart-package
          path: build
