name: 'configure-guides-step'
description: 'Configuration for Documentation render tool for typo3 documentation'

inputs:
  config:
    description: 'Configuration file location (i.e. "Documentation/")'
    default: 'Documentation'

  configure-branch:
    description: 'guides.xml configuration override (optional): Name of rendered GIT branch (i.e. "main" or "9.5"). Overrides <extension edit-on-github-branch="X">'
    default: ''

  configure-project-release:
    description: 'guides.xml configuration override (optional): Project release version (i.e. "draft" or "main"), based on deployment target directory. Overrides <project release="X">'
    default: ''

  configure-project-version:
    description: 'guides.xml configuration override (optional): Project version (i.e. "draft", "main", "9.5"). Overrides <project version="X">'
    default: ''

runs:
  using: 'docker'
  image: 'docker://ghcr.io/TYPO3-Documentation/render-guides:main'
  env:
    SHELL_VERBOSITY: '3'
  args:
    - 'configure'
    - '--project-release="${{ inputs.configure-project-release }}"'
    - '--project-version="${{ inputs.configure-project-version }}"'
    - '--extension-class="\T3Docs\Typo3DocsTheme\DependencyInjection\Typo3DocsThemeExtension"'
    - '--extension-attribute="edit-on-github-branch"'
    - '--extension-value="${{ inputs.configure-branch }}"'
    - '${{ inputs.config }}'

branding:
  icon: 'book-open'
  color: 'orange'
