#!/usr/bin/env bash

# very basic pre-commit hook
# just runs 'make pre-commit-test'
ABORT_ON_ERROR=yes
echo "Checking coding guidelines via 'make pre-commit-test' ..."

# This variable reflects what is configured in the Makefile, but does not use a TTY
# If this is changed or gets changed, always harmonize that with the entry in the 
# Makefile
PHP_BIN="docker run -i --rm --user=$(id -u):$(id -g) -v${PWD}:/opt/project -w /opt/project php:8.2-cli php -d memory_limit=1024M"
make PHP_BIN="$PHP_BIN" pre-commit-test 2>&1

ERROR_CODE=$?

if [ ${ERROR_CODE} -ne 0 ];then
    echo -e "\n-----------------------------------------------------------------\n"
    echo -e "  >> ERROR: There was a coding guideline problem in one or more of  "
    echo -e "              your files.                                           "
    echo -e "------------------------------------------------------------------\n"
    if [[ ${ABORT_ON_ERROR} == "yes" ]];then
        echo -e "   Your commit is being aborted ... Fix and try again!          "
        USE_EXIT_CODE=1
    else
        echo -e "   You must fix this and then commit again (git commit --amend) "
    fi
fi

exit ${USE_EXIT_CODE}
