on:
  push:
    branches:
      - main
  pull_request: null
  release:
    types:
      - published

env:
  DEFAULT_PHP_VERSION: "8.1"
  RUN_ENVIRONMENT: "local"

name: Phar
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ env.DEFAULT_PHP_VERSION }}"
          tools: "composer"

      - name: "Create phar"
        run: "make build-phar ENV=${{ env.RUN_ENVIRONMENT }}"

      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: phar
          path: .Build/*
          if-no-files-found: error
          retention-days: 1
