name: "Sub-split Publishing"
# See Documentation/Developer/MonoRepository.rst for details
# on Sub-tree splitting

on: # yamllint disable-line rule:truthy
  create:
    tags:
      - "*.*.*"
  delete:
    tags:
      - "*.*.*"
  push:
    paths:
      - "packages/**/*"
    branches:
      - "main"

jobs:
  publish_sub_splits:
    runs-on: "ubuntu-latest"
    name: "Publish Sub-split"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: "0"
          persist-credentials: "false"
      - uses: "frankdejonge/use-github-token@1.0.2"
        with:
          authentication: "typo3-documentation-team:${{ secrets.BOT_TOKEN }}"
          user_name: "TYPO3 Documentation Team"
          user_email: "documentation-automation@typo3.com"
      - name: "Cache splitsh-lite"
        id: "splitsh-cache"
        uses: "actions/cache@v4"
        with:
          path: "./.splitsh"
          key: "${{ runner.os }}-splitsh-d-101"
      - uses: "frankdejonge/use-subsplit-publish@1.0.0"
        with:
          source-branch: "main"
          config-path: "./config.subsplit-publish.json"
          splitsh-path: "./.splitsh/splitsh-lite"
          splitsh-version: "v1.0.1"
