name: "Sub-split Publishing"
# See Documentation/Developer/MonoRepository.rst for details
# on Sub-tree splitting

on: # yamllint disable-line rule:truthy
  create:
    tags:
      - "*.*.*"
  delete:
    tags:
      - "*.*.*"
  push:
    paths:
      - "packages/**/*"
    branches:
      - "main"

jobs:
  publish_sub_splits:
    runs-on: "ubuntu-latest"
    name: "Publish Sub-split"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: "0"
          persist-credentials: "false"
      - uses: frankdejonge/use-github-token@ae451b947d7d5975ca9aaadf04655bbd75dfbd85
        with:
          authentication: "typo3-documentation-team:${{ secrets.BOT_TOKEN }}"
          user_name: "TYPO3 Documentation Team"
          user_email: "documentation-automation@typo3.com"
      - name: "Cache splitsh-lite"
        id: "splitsh-cache"
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: "./.splitsh"
          key: "${{ runner.os }}-splitsh-d-101"
      - uses: frankdejonge/use-subsplit-publish@0001015147267203898034927e8cccad3a7a9aa7
        with:
          source-branch: "main"
          config-path: "./config.subsplit-publish.json"
          splitsh-path: "./.splitsh/splitsh-lite"
          splitsh-version: "v1.0.1"
